services:
  web:
    build: .
    container_name: flask_app
    env_file:
      - .env
    ports:
      - "5050:5050"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: decisionhub
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./decisionhub.sql:/docker-entrypoint-initdb.d/decisionhub.sql:ro

volumes:
  pgdata:
